// MANUEL RENK DÜZELTMELERİ
//
// Python görsel analizi bazı skinler için yanlış sonuç veriyor:
// - Tahta gövde/kabza yüzünden ana skin rengini kaçırıyor
// - Çok küçük vurgu renkleri (Redline'ın ince kırmızı bandı) atlanıyor
// - Karmaşık desenler (Wild Lotus, Fire Serpent) hatalı sınıflandırılıyor
//
// Bu dosya popüler skinler için DOĞRU renkleri içerir.
// Sıralama: Python görseli ezilir > Manuel renk düzeltme (BU DOSYA) > Otomatik isim etiketi.
//
// Format: 'Tam skin ismi': ['renk1', 'renk2', ...]
// Sadece renkleri içermesi yeterli — stiller (cyberpunk, vintage, vs.) Python'dan alınır.

export const MANUAL_COLOR_OVERRIDES: Record<string, string[]> = {
  // ====== AK-47 — kırmızı/turuncu spektrum ======
  'AK-47 | Redline': ['red', 'black'],
  'AK-47 | Fire Serpent': ['red', 'orange'],
  'AK-47 | Wild Lotus': ['red', 'white'],
  'AK-47 | Bloodsport': ['red', 'pink'],
  'AK-47 | Inheritance': ['red', 'gold'],
  'AK-47 | The Empress': ['red', 'gold'],
  'AK-47 | Searing Rage': ['red', 'orange'],
  'AK-47 | Red Laminate': ['red'],
  'AK-47 | Cartel': ['gold', 'black'],
  'AK-47 | Phantom Disruptor': ['purple', 'blue'],
  'AK-47 | Head Shot': ['black', 'red'],
  'AK-47 | First Class Ticket': ['gold', 'red'],

  // AK-47 — mavi spektrum
  'AK-47 | Vulcan': ['blue', 'white'],
  'AK-47 | Ice Coaled': ['blue', 'white'],
  'AK-47 | Frontside Misty': ['blue'],
  'AK-47 | Blue Laminate': ['blue'],
  'AK-47 | Aquamarine Revenge': ['blue'],
  'AK-47 | Point Disarray': ['blue', 'orange'],
  'AK-47 | Leet Museo': ['blue', 'orange'],
  'AK-47 | Orbit Mk01': ['blue', 'green'],

  // AK-47 — yeşil spektrum
  'AK-47 | Hydroponic': ['green'],
  'AK-47 | Emerald Pinstripe': ['green', 'black'],
  'AK-47 | Jet Set': ['green', 'gold'],
  'AK-47 | Jaguar': ['green', 'black'],
  'AK-47 | Green Laminate': ['green'],
  'AK-47 | Predator': ['green', 'black'],
  'AK-47 | Safari Mesh': ['green'],

  // AK-47 — mor/pembe
  'AK-47 | Neon Rider': ['pink', 'purple'],
  'AK-47 | Neon Revolution': ['purple', 'pink'],
  'AK-47 | Nightwish': ['purple', 'pink'],
  'AK-47 | Baroque Purple': ['purple', 'black'],
  'AK-47 | Aloha': ['blue', 'pink'],

  // AK-47 — siyah/altın
  'AK-47 | Slate': ['black'],
  'AK-47 | Black Laminate': ['black'],
  'AK-47 | Steel Delta': ['black'],
  'AK-47 | Gold Arabesque': ['gold', 'black'],
  'AK-47 | Legion of Anubis': ['gold', 'black'],
  'AK-47 | Case Hardened': ['gold', 'blue'],

  // AK-47 — turuncu
  'AK-47 | Asiimov': ['orange', 'white', 'black'],
  'AK-47 | Wasteland Rebel': ['orange', 'green'],
  'AK-47 | Rat Rod': ['orange'],
  'AK-47 | Elite Build': ['orange'],
  'AK-47 | Safety Net': ['orange'],

  // ====== M4A4 ======
  'M4A4 | Howl': ['red', 'white'],
  'M4A4 | The Emperor': ['gold', 'red'],
  'M4A4 | Hellfire': ['red', 'orange', 'pink'],
  'M4A4 | Asiimov': ['orange', 'white', 'black'],
  'M4A4 | Neo-Noir': ['pink', 'purple'],
  'M4A4 | Bullet Rain': ['red', 'black'],
  'M4A4 | Buzz Kill': ['green', 'purple'],
  'M4A4 | The Battlestar': ['red', 'blue'],
  'M4A4 | Cyber Security': ['blue', 'green'],
  'M4A4 | Desert-Strike': ['orange', 'gold'],
  'M4A4 | Royal Paladin': ['white', 'blue', 'gold'],
  'M4A4 | Tornado': ['blue', 'white'],
  'M4A4 | Dragon King': ['blue', 'red'],
  'M4A4 | Spider Lily': ['red', 'black'],
  'M4A4 | Eye of Horus': ['gold', 'black'],
  'M4A4 | Daybreak': ['blue', 'orange'],
  'M4A4 | In Living Color': ['pink', 'purple'],
  'M4A4 | Choppa': ['red', 'black'],
  'M4A4 | Poseidon': ['blue', 'white'],
  'M4A4 | Griffin': ['white', 'red'],
  'M4A4 | The Coalition': ['orange', 'red'],
  'M4A4 | Magnesium': ['orange', 'black'],

  // ====== M4A1-S ======
  'M4A1-S | Hot Rod': ['red', 'orange'],
  'M4A1-S | Knight': ['white', 'gold'],
  'M4A1-S | Hyper Beast': ['pink', 'blue', 'purple'],
  'M4A1-S | Printstream': ['white', 'black'],
  'M4A1-S | Welcome to the Jungle': ['green', 'orange'],
  'M4A1-S | Cyrex': ['white', 'red'],
  'M4A1-S | Mecha Industries': ['blue', 'orange'],
  'M4A1-S | Decimator': ['pink', 'purple'],
  'M4A1-S | Master Piece': ['white', 'pink'],
  'M4A1-S | Player Two': ['pink', 'white'],
  'M4A1-S | Golden Coil': ['gold', 'black'],
  'M4A1-S | Icarus Fell': ['white', 'gold'],
  'M4A1-S | Imminent Danger': ['orange', 'red'],
  'M4A1-S | Briefing': ['white', 'blue'],
  'M4A1-S | Black Lotus': ['black', 'pink'],
  'M4A1-S | Leaded Glass': ['blue', 'red'],
  'M4A1-S | Bright Water': ['blue', 'white'],
  'M4A1-S | Guardian': ['blue', 'white'],
  'M4A1-S | Nightmare': ['black', 'red'],
  'M4A1-S | Basilisk': ['green'],
  'M4A1-S | Blue Phosphor': ['blue'],
  "M4A1-S | Chantico's Fire": ['orange', 'red', 'gold'],
  'M4A1-S | Flashback': ['blue', 'white'],

  // ====== AWP ======
  'AWP | Dragon Lore': ['gold', 'green'],
  'AWP | Medusa': ['green', 'gold'],
  'AWP | Wildfire': ['red', 'orange', 'gold'],
  'AWP | Asiimov': ['orange', 'white', 'black'],
  'AWP | Neo-Noir': ['pink', 'purple'],
  'AWP | Hyper Beast': ['pink', 'blue', 'purple'],
  'AWP | Lightning Strike': ['blue', 'white'],
  'AWP | Containment Breach': ['orange', 'green'],
  'AWP | Fade': ['pink', 'purple'],
  'AWP | Printstream': ['white', 'black'],
  'AWP | Chromatic Aberration': ['blue', 'pink'],
  'AWP | Mortis': ['black', 'gold'],
  'AWP | Atheris': ['green', 'black'],
  'AWP | Redline': ['red', 'black'],
  'AWP | Electric Hive': ['blue', 'green'],
  'AWP | Worm God': ['green', 'black'],
  'AWP | Boom': ['white', 'red'],
  'AWP | Desert Hydra': ['orange', 'red', 'gold'],
  'AWP | Sun in Leo': ['gold', 'white'],
  'AWP | Black Nile': ['black', 'gold'],
  'AWP | Phobos': ['black', 'orange'],
  'AWP | Oni Taiji': ['red', 'white'],
  'AWP | Acheron': ['black', 'orange'],
  'AWP | Capillary': ['red', 'white'],
  'AWP | Ice Coaled': ['blue', 'white'],
  'AWP | Fever Dream': ['pink', 'purple'],
  'AWP | CMYK': ['blue', 'pink'],
  'AWP | Pit Viper': ['green', 'black'],
  'AWP | Corticera': ['blue', 'red'],
  'AWP | PAW': ['blue', 'green'],

  // ====== Glock-18 ======
  'Glock-18 | Fade': ['pink', 'purple', 'orange'],
  'Glock-18 | Water Elemental': ['blue', 'white'],
  'Glock-18 | Gamma Doppler': ['green'],
  'Glock-18 | Twilight Galaxy': ['purple', 'blue'],
  'Glock-18 | Wasteland Rebel': ['orange', 'green'],
  'Glock-18 | Bullet Queen': ['blue', 'gold'],
  'Glock-18 | Off World': ['blue'],
  'Glock-18 | Vogue': ['pink', 'red', 'black'],
  'Glock-18 | AXIA': ['black', 'gold'],
  'Glock-18 | Royal Legion': ['gold', 'white'],
  'Glock-18 | Bunsen Burner': ['blue', 'orange'],
  'Glock-18 | Neo-Noir': ['pink', 'purple'],
  'Glock-18 | Nuclear Garden': ['green'],
  'Glock-18 | Reactor': ['green'],
  'Glock-18 | Snack Attack': ['pink', 'red'],
  'Glock-18 | Dragon Tattoo': ['blue', 'red'],

  // ====== USP-S ======
  'USP-S | Kill Confirmed': ['black', 'white', 'red'],
  'USP-S | Printstream': ['white', 'black'],
  'USP-S | Neo-Noir': ['pink', 'purple'],
  'USP-S | The Traitor': ['black', 'red'],
  'USP-S | Whiteout': ['white', 'black'],
  'USP-S | Cyrex': ['white', 'red'],
  'USP-S | Caiman': ['green', 'black'],
  'USP-S | Overgrowth': ['green', 'orange'],
  'USP-S | Orion': ['black', 'gold'],
  'USP-S | Monster Mashup': ['purple', 'green'],
  'USP-S | Torque': ['orange', 'black'],
  'USP-S | Blueprint': ['blue', 'white'],
  'USP-S | Cortex': ['orange'],
  'USP-S | Black Lotus': ['black', 'pink'],
  'USP-S | Ticket to Hell': ['black', 'red'],
  'USP-S | Jawbreaker': ['pink', 'blue'],

  // ====== Desert Eagle ======
  'Desert Eagle | Blaze': ['orange', 'red'],
  'Desert Eagle | Code Red': ['red', 'black'],
  'Desert Eagle | Printstream': ['white', 'black'],
  'Desert Eagle | Kumicho Dragon': ['black', 'orange'],
  'Desert Eagle | Crimson Web': ['red', 'black'],
  'Desert Eagle | Golden Koi': ['gold', 'white'],
  'Desert Eagle | Hand Cannon': ['gold', 'black'],
  'Desert Eagle | Heirloom': ['gold'],
  'Desert Eagle | Hypnotic': ['gold', 'black'],
  'Desert Eagle | Naga': ['green', 'black'],
  'Desert Eagle | Sunset Storm 壱': ['orange', 'red'],
  'Desert Eagle | Sunset Storm 弐': ['blue', 'purple'],
  'Desert Eagle | Cobalt Disruption': ['blue'],
  'Desert Eagle | Mecha Industries': ['blue', 'orange'],
  'Desert Eagle | Light Rail': ['blue', 'orange'],
  'Desert Eagle | Trigger Discipline': ['blue', 'gold'],
  'Desert Eagle | Conspiracy': ['gold', 'black'],
  'Desert Eagle | Heat Treated': ['blue', 'gold'],
  'Desert Eagle | Ocean Drive': ['pink'],
  'Desert Eagle | Pilot': ['black', 'orange'],
  'Desert Eagle | Bronze Deco': ['orange', 'gold'],
  'Desert Eagle | Emerald Jörmungandr': ['green', 'gold'],
  'Desert Eagle | Midnight Storm': ['blue', 'black'],

  // ====== Karambit ======
  '★ Karambit | Fade': ['pink', 'purple'],
  '★ Karambit | Doppler': ['pink', 'purple'],
  '★ Karambit | Marble Fade': ['pink', 'red'],
  '★ Karambit | Tiger Tooth': ['gold', 'orange'],
  '★ Karambit | Crimson Web': ['red', 'black'],
  '★ Karambit | Slaughter': ['red'],
  '★ Karambit | Lore': ['gold', 'green'],
  '★ Karambit | Autotronic': ['black'],
  '★ Karambit | Black Laminate': ['black'],
  '★ Karambit | Case Hardened': ['blue', 'gold'],
  '★ Karambit | Damascus Steel': ['black', 'white'],
  '★ Karambit | Stained': ['black'],
  '★ Karambit | Ultraviolet': ['purple'],
  '★ Karambit | Bright Water': ['blue', 'white'],
  '★ Karambit | Rust Coat': ['orange'],
  '★ Karambit | Forest DDPAT': ['green'],
  '★ Karambit | Blue Steel': ['blue'],
  '★ Karambit | Boreal Forest': ['green'],
  '★ Karambit | Safari Mesh': ['orange'],
  '★ Karambit | Gamma Doppler': ['green'],
  '★ Karambit | Night': ['black'],
  '★ Karambit | Scorched': ['orange', 'black'],
  '★ Karambit | Urban Masked': ['black', 'white'],
  '★ Karambit | Vanilla': ['black'],

  // ====== Butterfly Knife ======
  '★ Butterfly Knife | Fade': ['pink', 'purple'],
  '★ Butterfly Knife | Doppler': ['pink', 'purple'],
  '★ Butterfly Knife | Marble Fade': ['pink', 'red'],
  '★ Butterfly Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Butterfly Knife | Crimson Web': ['red', 'black'],
  '★ Butterfly Knife | Slaughter': ['red'],
  '★ Butterfly Knife | Lore': ['gold', 'green'],
  '★ Butterfly Knife | Case Hardened': ['blue', 'gold'],
  '★ Butterfly Knife | Ultraviolet': ['purple'],
  '★ Butterfly Knife | Gamma Doppler': ['green'],
  '★ Butterfly Knife | Safari Mesh': ['orange'],

  // ====== Diğer popüler bıçaklar ======
  '★ Bayonet | Fade': ['pink', 'purple'],
  '★ Bayonet | Doppler': ['pink', 'purple'],
  '★ Bayonet | Marble Fade': ['pink', 'red'],
  '★ Bayonet | Tiger Tooth': ['gold', 'orange'],
  '★ Bayonet | Crimson Web': ['red', 'black'],
  '★ Bayonet | Lore': ['gold', 'green'],
  '★ Bayonet | Case Hardened': ['blue', 'gold'],

  '★ M9 Bayonet | Fade': ['pink', 'purple'],
  '★ M9 Bayonet | Doppler': ['pink', 'purple'],
  '★ M9 Bayonet | Marble Fade': ['pink', 'red'],
  '★ M9 Bayonet | Tiger Tooth': ['gold', 'orange'],
  '★ M9 Bayonet | Crimson Web': ['red', 'black'],
  '★ M9 Bayonet | Lore': ['gold', 'green'],
  '★ M9 Bayonet | Case Hardened': ['blue', 'gold'],

  '★ Talon Knife | Fade': ['pink', 'purple'],
  '★ Talon Knife | Doppler': ['pink', 'purple'],
  '★ Talon Knife | Marble Fade': ['pink', 'red'],
  '★ Talon Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Talon Knife | Crimson Web': ['red', 'black'],
  '★ Talon Knife | Case Hardened': ['blue', 'gold'],

  '★ Stiletto Knife | Fade': ['pink', 'purple'],
  '★ Stiletto Knife | Doppler': ['pink', 'purple'],
  '★ Stiletto Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Stiletto Knife | Crimson Web': ['red', 'black'],
  '★ Stiletto Knife | Case Hardened': ['blue', 'gold'],

  '★ Skeleton Knife | Crimson Web': ['red', 'black'],
  '★ Skeleton Knife | Fade': ['pink', 'purple'],
  '★ Skeleton Knife | Tiger Tooth': ['gold', 'orange'],

  '★ Flip Knife | Fade': ['pink', 'purple'],
  '★ Flip Knife | Doppler': ['pink', 'purple'],
  '★ Flip Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Flip Knife | Crimson Web': ['red', 'black'],

  '★ Huntsman Knife | Fade': ['pink', 'purple'],
  '★ Huntsman Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Huntsman Knife | Crimson Web': ['red', 'black'],

  // ====== Sport Gloves ======
  "★ Sport Gloves | Pandora's Box": ['blue', 'purple'],
  '★ Sport Gloves | Vice': ['pink', 'purple'],
  '★ Sport Gloves | Superconductor': ['blue', 'pink'],
  '★ Sport Gloves | Hedge Maze': ['green', 'orange'],
  '★ Sport Gloves | Omega': ['orange', 'gold'],
  '★ Sport Gloves | Slingshot': ['orange', 'red'],
  '★ Sport Gloves | Amphibious': ['blue', 'green'],
  '★ Sport Gloves | Big Game': ['orange', 'black'],
  '★ Sport Gloves | Nocts': ['black', 'gold'],
  '★ Sport Gloves | Scarlet Shamagh': ['red', 'black'],

  // ====== Driver Gloves ======
  '★ Driver Gloves | Crimson Weave': ['red', 'black'],
  '★ Driver Gloves | King Snake': ['green', 'black'],
  '★ Driver Gloves | Imperial Plaid': ['red', 'black'],
  '★ Driver Gloves | Rezan the Red': ['red'],
  '★ Driver Gloves | Lunar Weave': ['white', 'black'],
  '★ Driver Gloves | Black Tie': ['black', 'gold'],
  '★ Driver Gloves | Snow Leopard': ['white'],
  '★ Driver Gloves | Diamondback': ['black', 'gold'],
  '★ Driver Gloves | Racing Green': ['green', 'black'],
  '★ Driver Gloves | Convoy': ['green'],

  // ====== Specialist Gloves ======
  '★ Specialist Gloves | Crimson Kimono': ['red', 'black'],
  '★ Specialist Gloves | Crimson Web': ['red', 'black'],
  '★ Specialist Gloves | Marble Fade': ['pink', 'red'],
  '★ Specialist Gloves | Fade': ['pink', 'purple'],
  '★ Specialist Gloves | Tiger Strike': ['orange', 'black'],
  '★ Specialist Gloves | Emerald Web': ['green', 'black'],
  '★ Specialist Gloves | Foundation': ['orange', 'gold'],
  '★ Specialist Gloves | Buckshot': ['orange', 'gold'],
  '★ Specialist Gloves | Field Agent': ['black', 'orange'],
  '★ Specialist Gloves | Mogul': ['purple', 'black'],
};
