// Manuel renk/tema etiket veritabanı
// Her skin için görselindeki ASIL renkler (isimden değil, gerçek görselden)
// Anahtarlar: skin'in tam ismi (★ ve | dahil)

export const MANUAL_TAGS: Record<string, string[]> = {
  // ====== AK-47 ======
  'AK-47 | Redline': ['red', 'black'],
  'AK-47 | Fire Serpent': ['red', 'orange', 'premium'],
  'AK-47 | Wild Lotus': ['red', 'white', 'premium'],
  'AK-47 | Bloodsport': ['red', 'pink'],
  'AK-47 | Inheritance': ['red', 'gold'],
  'AK-47 | The Empress': ['red', 'gold', 'premium'],
  'AK-47 | Searing Rage': ['red', 'orange'],
  'AK-47 | Red Laminate': ['red', 'vintage'],
  'AK-47 | Hydroponic': ['green'],
  'AK-47 | Emerald Pinstripe': ['green', 'black'],
  'AK-47 | Jet Set': ['green', 'gold'],
  'AK-47 | Jaguar': ['green', 'black'],
  'AK-47 | Green Laminate': ['green', 'vintage'],
  'AK-47 | Slate': ['black'],
  'AK-47 | Black Laminate': ['black', 'vintage'],
  'AK-47 | Ice Coaled': ['blue', 'white'],
  'AK-47 | Frontside Misty': ['blue', 'cyberpunk'],
  'AK-47 | Blue Laminate': ['blue', 'vintage'],
  'AK-47 | Vulcan': ['blue', 'white'],
  'AK-47 | Point Disarray': ['blue', 'orange'],
  'AK-47 | Neon Rider': ['pink', 'purple', 'cyberpunk', 'neon'],
  'AK-47 | Neon Revolution': ['purple', 'pink', 'cyberpunk', 'neon'],
  'AK-47 | Asiimov': ['orange', 'white', 'black', 'cyberpunk'],
  'AK-47 | Orbit Mk01': ['blue', 'green'],
  'AK-47 | Gold Arabesque': ['gold', 'black', 'premium'],
  'AK-47 | Case Hardened': ['blue', 'gold', 'vintage'],
  'AK-47 | Cartel': ['gold', 'black'],
  'AK-47 | Wasteland Rebel': ['orange', 'green', 'vintage'],
  'AK-47 | Phantom Disruptor': ['purple', 'blue'],
  'AK-47 | Legion of Anubis': ['gold', 'black', 'vintage'],
  'AK-47 | Aquamarine Revenge': ['blue', 'cyberpunk'],
  'AK-47 | Leet Museo': ['blue', 'orange'],
  'AK-47 | First Class Ticket': ['gold', 'red'],
  'AK-47 | Nightwish': ['purple', 'pink', 'cyberpunk'],
  'AK-47 | Steel Delta': ['gray', 'black'],
  'AK-47 | Predator': ['green', 'black'],
  'AK-47 | Elite Build': ['orange', 'gray'],
  'AK-47 | Safety Net': ['orange', 'yellow'],
  'AK-47 | Frontline': ['black', 'gray', 'military'],
  'AK-47 | Cliffhanger': ['gray', 'black'],
  'AK-47 | Baroque Purple': ['purple', 'black', 'vintage'],
  'AK-47 | Rat Rod': ['orange', 'vintage'],
  'AK-47 | Head Shot': ['black', 'red'],
  'AK-47 | Aloha': ['blue', 'pink'],

  // ====== M4A4 ======
  'M4A4 | Howl': ['red', 'white', 'premium'],
  'M4A4 | The Emperor': ['gold', 'red', 'premium'],
  'M4A4 | Hellfire': ['red', 'orange', 'pink'],
  'M4A4 | Asiimov': ['orange', 'white', 'black', 'cyberpunk'],
  'M4A4 | Neo-Noir': ['pink', 'purple', 'cyberpunk', 'neon'],
  'M4A4 | Bullet Rain': ['red', 'black'],
  'M4A4 | Buzz Kill': ['green', 'purple', 'neon'],
  'M4A4 | The Battlestar': ['red', 'blue'],
  'M4A4 | Cyber Security': ['blue', 'green', 'cyberpunk'],
  'M4A4 | Desert-Strike': ['orange', 'gold', 'military'],
  'M4A4 | Royal Paladin': ['white', 'blue', 'gold'],
  'M4A4 | Tornado': ['blue', 'white'],
  'M4A4 | Magnesium': ['orange', 'black'],
  'M4A4 | Dragon King': ['blue', 'red'],
  'M4A4 | Spider Lily': ['red', 'black'],
  'M4A4 | Modern Hunter': ['orange', 'black'],
  'M4A4 | Eye of Horus': ['gold', 'black', 'premium'],
  'M4A4 | Daybreak': ['blue', 'orange'],
  'M4A4 | In Living Color': ['pink', 'purple', 'neon'],
  'M4A4 | Tooth Fairy': ['blue', 'pink'],
  'M4A4 | Choppa': ['red', 'black'],
  'M4A4 | Poseidon': ['blue', 'white', 'premium'],
  'M4A4 | Griffin': ['white', 'red'],

  // ====== M4A1-S ======
  'M4A1-S | Hot Rod': ['red', 'orange'],
  'M4A1-S | Knight': ['white', 'gold', 'vintage'],
  'M4A1-S | Hyper Beast': ['pink', 'blue', 'purple', 'neon'],
  'M4A1-S | Printstream': ['white', 'black'],
  'M4A1-S | Welcome to the Jungle': ['green', 'orange'],
  'M4A1-S | Cyrex': ['white', 'red', 'cyberpunk'],
  'M4A1-S | Mecha Industries': ['blue', 'orange', 'cyberpunk'],
  'M4A1-S | Decimator': ['pink', 'purple', 'cyberpunk', 'neon'],
  'M4A1-S | Master Piece': ['white', 'pink'],
  'M4A1-S | Player Two': ['pink', 'white'],
  'M4A1-S | Golden Coil': ['gold', 'black'],
  'M4A1-S | Icarus Fell': ['white', 'gold', 'vintage'],
  'M4A1-S | Imminent Danger': ['orange', 'red'],
  'M4A1-S | Briefing': ['white', 'blue'],
  'M4A1-S | Mud-Spec': ['gray', 'orange', 'military'],
  'M4A1-S | Night Terror': ['black', 'purple'],
  'M4A1-S | Black Lotus': ['black', 'pink'],
  'M4A1-S | Leaded Glass': ['blue', 'red', 'green'],
  'M4A1-S | Emphorosaur-S': ['white', 'gold'],
  'M4A1-S | Boreal Forest': ['green', 'military'],
  'M4A1-S | Atomic Alloy': ['orange', 'red'],
  'M4A1-S | Bright Water': ['blue', 'white'],
  'M4A1-S | Guardian': ['blue', 'white'],
  'M4A1-S | Nightmare': ['black', 'red'],
  'M4A1-S | Basilisk': ['green'],
  'M4A1-S | Blue Phosphor': ['blue', 'neon'],
  'M4A1-S | Chantico\'s Fire': ['orange', 'red', 'gold'],
  'M4A1-S | Flashback': ['blue', 'white'],
  'M4A1-S | Players Trigger': ['black'],
  'M4A1-S | Wash me plz': ['gray'],

  // ====== AWP ======
  'AWP | Dragon Lore': ['gold', 'green', 'premium'],
  'AWP | Medusa': ['green', 'gold', 'premium'],
  'AWP | Wildfire': ['red', 'orange', 'gold'],
  'AWP | Asiimov': ['orange', 'white', 'black', 'cyberpunk'],
  'AWP | Neo-Noir': ['pink', 'purple', 'cyberpunk', 'neon'],
  'AWP | Hyper Beast': ['pink', 'blue', 'purple', 'neon'],
  'AWP | Lightning Strike': ['blue', 'white'],
  'AWP | Containment Breach': ['orange', 'green'],
  'AWP | Fade': ['pink', 'purple', 'doppler-family'],
  'AWP | Printstream': ['white', 'black'],
  'AWP | Chromatic Aberration': ['blue', 'pink', 'cyberpunk'],
  'AWP | Mortis': ['black', 'gold'],
  'AWP | Atheris': ['green', 'black'],
  'AWP | Redline': ['red', 'black'],
  'AWP | Electric Hive': ['blue', 'green', 'neon'],
  'AWP | Worm God': ['green', 'black'],
  'AWP | Boom': ['white', 'red'],
  'AWP | Pink DDPAT': ['pink', 'military'],
  'AWP | Snake Camo': ['green', 'military'],
  'AWP | Desert Hydra': ['orange', 'red', 'gold'],
  'AWP | Sun in Leo': ['gold', 'white'],
  'AWP | Black Nile': ['black', 'gold'],
  'AWP | Phobos': ['black', 'orange'],
  'AWP | Oni Taiji': ['red', 'white'],
  'AWP | Acheron': ['black', 'orange'],
  'AWP | Exoskeleton': ['white', 'black'],
  'AWP | Duality': ['blue', 'pink'],
  'AWP | Graphite': ['black'],
  'AWP | Capillary': ['red', 'white'],
  'AWP | Ice Coaled': ['blue', 'white'],
  'AWP | Fever Dream': ['pink', 'purple', 'neon'],

  // ====== AWP (popular cheap) ======
  'AWP | Safari Mesh': ['orange', 'military'],
  'AWP | Pit Viper': ['green', 'black'],
  'AWP | Corticera': ['blue', 'red'],

  // ====== Glock-18 ======
  'Glock-18 | Fade': ['pink', 'purple', 'orange', 'doppler-family'],
  'Glock-18 | Water Elemental': ['blue', 'white'],
  'Glock-18 | Gamma Doppler': ['green', 'doppler-family'],
  'Glock-18 | Twilight Galaxy': ['purple', 'blue'],
  'Glock-18 | Wasteland Rebel': ['orange', 'green'],
  'Glock-18 | Bullet Queen': ['blue', 'gold'],
  'Glock-18 | Off World': ['blue', 'cyberpunk'],
  'Glock-18 | Vogue': ['pink', 'red', 'black'],
  'Glock-18 | AXIA': ['black', 'gold', 'cyberpunk'],
  'Glock-18 | Royal Legion': ['gold', 'white'],
  'Glock-18 | Bunsen Burner': ['blue', 'orange'],
  'Glock-18 | Neo-Noir': ['pink', 'purple', 'cyberpunk'],
  'Glock-18 | Pink DDPAT': ['pink', 'military'],
  'Glock-18 | Nuclear Garden': ['green'],
  'Glock-18 | Brass': ['gold', 'orange'],
  'Glock-18 | Reactor': ['green', 'neon'],
  'Glock-18 | Snack Attack': ['pink', 'red'],
  'Glock-18 | Dragon Tattoo': ['blue', 'red'],

  // ====== USP-S ======
  'USP-S | Kill Confirmed': ['black', 'white', 'red'],
  'USP-S | Printstream': ['white', 'black'],
  'USP-S | Neo-Noir': ['pink', 'purple', 'cyberpunk'],
  'USP-S | The Traitor': ['black', 'red'],
  'USP-S | Whiteout': ['white', 'black'],
  'USP-S | Cyrex': ['white', 'red', 'cyberpunk'],
  'USP-S | Caiman': ['green', 'black'],
  'USP-S | Stainless': ['gray'],
  'USP-S | Overgrowth': ['green', 'orange'],
  'USP-S | Orion': ['black', 'gold'],
  'USP-S | Monster Mashup': ['purple', 'green'],
  'USP-S | Torque': ['orange', 'black'],
  'USP-S | Blueprint': ['blue', 'white'],
  'USP-S | Cortex': ['orange', 'gray'],
  'USP-S | Black Lotus': ['black', 'pink'],
  'USP-S | Ticket to Hell': ['black', 'red'],
  'USP-S | Jawbreaker': ['pink', 'blue'],
  'USP-S | Ancient Visions': ['orange', 'red'],

  // ====== Desert Eagle ======
  'Desert Eagle | Blaze': ['orange', 'red'],
  'Desert Eagle | Code Red': ['red', 'black'],
  'Desert Eagle | Printstream': ['white', 'black'],
  'Desert Eagle | Kumicho Dragon': ['black', 'orange'],
  'Desert Eagle | Crimson Web': ['red', 'black'],
  'Desert Eagle | Golden Koi': ['gold', 'white'],
  'Desert Eagle | Hand Cannon': ['gold', 'black'],
  'Desert Eagle | Heirloom': ['gold', 'vintage', 'premium'],
  'Desert Eagle | Hypnotic': ['gold', 'black'],
  'Desert Eagle | Naga': ['green', 'black'],
  'Desert Eagle | Sunset Storm 壱': ['orange', 'red'],
  'Desert Eagle | Sunset Storm 弐': ['blue', 'purple'],
  'Desert Eagle | Cobalt Disruption': ['blue', 'cyberpunk'],
  'Desert Eagle | Mecha Industries': ['blue', 'orange', 'cyberpunk'],
  'Desert Eagle | Light Rail': ['blue', 'orange'],
  'Desert Eagle | Trigger Discipline': ['blue', 'gold'],
  'Desert Eagle | Conspiracy': ['gold', 'black', 'premium'],
  'Desert Eagle | Heat Treated': ['blue', 'gold'],
  'Desert Eagle | Ocean Drive': ['pink', 'cyberpunk', 'neon'],
  'Desert Eagle | Pilot': ['black', 'orange'],
  'Desert Eagle | Bronze Deco': ['orange', 'gold'],
  'Desert Eagle | Emerald Jörmungandr': ['green', 'gold', 'premium'],
  'Desert Eagle | Midnight Storm': ['blue', 'black'],

  // ====== Knives (Karambit, Bayonet, etc) ======
  '★ Karambit | Fade': ['pink', 'purple', 'doppler-family', 'premium'],
  '★ Karambit | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Karambit | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Karambit | Tiger Tooth': ['gold', 'orange'],
  '★ Karambit | Crimson Web': ['red', 'black'],
  '★ Karambit | Slaughter': ['red'],
  '★ Karambit | Lore': ['gold', 'green', 'premium'],
  '★ Karambit | Autotronic': ['black', 'cyberpunk'],
  '★ Karambit | Black Laminate': ['black', 'vintage'],
  '★ Karambit | Case Hardened': ['blue', 'gold', 'vintage'],
  '★ Karambit | Damascus Steel': ['gray', 'vintage'],
  '★ Karambit | Stained': ['black', 'vintage'],
  '★ Karambit | Ultraviolet': ['purple'],
  '★ Karambit | Bright Water': ['blue', 'white'],
  '★ Karambit | Rust Coat': ['orange', 'vintage'],
  '★ Karambit | Forest DDPAT': ['green', 'military'],
  '★ Karambit | Blue Steel': ['blue'],
  '★ Karambit | Boreal Forest': ['green', 'military'],
  '★ Karambit | Safari Mesh': ['orange', 'military'],
  '★ Karambit | Gamma Doppler': ['green', 'doppler-family'],
  '★ Karambit | Night': ['black'],
  '★ Karambit | Scorched': ['orange', 'black'],
  '★ Karambit | Urban Masked': ['gray', 'military'],
  '★ Karambit | Vanilla': ['gray'],

  '★ Butterfly Knife | Fade': ['pink', 'purple', 'doppler-family', 'premium'],
  '★ Butterfly Knife | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Butterfly Knife | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Butterfly Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Butterfly Knife | Crimson Web': ['red', 'black'],
  '★ Butterfly Knife | Slaughter': ['red'],
  '★ Butterfly Knife | Lore': ['gold', 'green', 'premium'],
  '★ Butterfly Knife | Autotronic': ['black', 'cyberpunk'],
  '★ Butterfly Knife | Case Hardened': ['blue', 'gold', 'vintage'],
  '★ Butterfly Knife | Ultraviolet': ['purple'],
  '★ Butterfly Knife | Gamma Doppler': ['green', 'doppler-family'],

  '★ Bayonet | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Bayonet | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Bayonet | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Bayonet | Tiger Tooth': ['gold', 'orange'],
  '★ Bayonet | Crimson Web': ['red', 'black'],
  '★ Bayonet | Slaughter': ['red'],
  '★ Bayonet | Lore': ['gold', 'green', 'premium'],
  '★ Bayonet | Autotronic': ['black', 'cyberpunk'],
  '★ Bayonet | Case Hardened': ['blue', 'gold', 'vintage'],
  '★ Bayonet | Ultraviolet': ['purple'],
  '★ Bayonet | Gamma Doppler': ['green', 'doppler-family'],
  '★ Bayonet | Night': ['black'],

  '★ Talon Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Talon Knife | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Talon Knife | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Talon Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Talon Knife | Crimson Web': ['red', 'black'],
  '★ Talon Knife | Slaughter': ['red'],
  '★ Talon Knife | Lore': ['gold', 'green', 'premium'],
  '★ Talon Knife | Autotronic': ['black', 'cyberpunk'],
  '★ Talon Knife | Case Hardened': ['blue', 'gold', 'vintage'],
  '★ Talon Knife | Gamma Doppler': ['green', 'doppler-family'],

  '★ M9 Bayonet | Fade': ['pink', 'purple', 'doppler-family'],
  '★ M9 Bayonet | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ M9 Bayonet | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ M9 Bayonet | Tiger Tooth': ['gold', 'orange'],
  '★ M9 Bayonet | Crimson Web': ['red', 'black'],
  '★ M9 Bayonet | Lore': ['gold', 'green', 'premium'],
  '★ M9 Bayonet | Case Hardened': ['blue', 'gold', 'vintage'],
  '★ M9 Bayonet | Gamma Doppler': ['green', 'doppler-family'],

  '★ Flip Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Flip Knife | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Flip Knife | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Flip Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Flip Knife | Crimson Web': ['red', 'black'],
  '★ Flip Knife | Lore': ['gold', 'green', 'premium'],
  '★ Flip Knife | Case Hardened': ['blue', 'gold', 'vintage'],

  '★ Stiletto Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Stiletto Knife | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Stiletto Knife | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Stiletto Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Stiletto Knife | Crimson Web': ['red', 'black'],
  '★ Stiletto Knife | Case Hardened': ['blue', 'gold', 'vintage'],

  '★ Huntsman Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Huntsman Knife | Doppler': ['pink', 'purple', 'doppler-family'],
  '★ Huntsman Knife | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Huntsman Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Huntsman Knife | Crimson Web': ['red', 'black'],
  '★ Huntsman Knife | Case Hardened': ['blue', 'gold', 'vintage'],

  '★ Bowie Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Bowie Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Bowie Knife | Crimson Web': ['red', 'black'],
  '★ Bowie Knife | Lore': ['gold', 'green'],

  '★ Ursus Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Ursus Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Ursus Knife | Crimson Web': ['red', 'black'],

  '★ Navaja Knife | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Navaja Knife | Tiger Tooth': ['gold', 'orange'],
  '★ Navaja Knife | Crimson Web': ['red', 'black'],

  '★ Paracord Knife | Crimson Web': ['red', 'black'],
  '★ Paracord Knife | Blue Steel': ['blue'],
  '★ Survival Knife | Crimson Web': ['red', 'black'],
  '★ Skeleton Knife | Crimson Web': ['red', 'black'],
  '★ Nomad Knife | Crimson Web': ['red', 'black'],
  '★ Classic Knife | Crimson Web': ['red', 'black'],
  '★ Kukri Knife | Crimson Web': ['red', 'black'],
  '★ Shadow Daggers | Crimson Web': ['red', 'black'],
  '★ Shadow Daggers | Autotronic': ['black', 'cyberpunk'],

  // ====== Gloves ======
  '★ Sport Gloves | Pandora\'s Box': ['blue', 'purple', 'premium'],
  '★ Sport Gloves | Vice': ['pink', 'purple', 'cyberpunk', 'neon'],
  '★ Sport Gloves | Superconductor': ['blue', 'pink', 'neon'],
  '★ Sport Gloves | Hedge Maze': ['green', 'orange'],
  '★ Sport Gloves | Omega': ['orange', 'gold'],
  '★ Sport Gloves | Slingshot': ['orange', 'red'],
  '★ Sport Gloves | Amphibious': ['blue', 'green'],
  '★ Sport Gloves | Big Game': ['orange', 'black'],
  '★ Sport Gloves | Nocts': ['black', 'gold'],
  '★ Sport Gloves | Scarlet Shamagh': ['red', 'black'],

  '★ Driver Gloves | Crimson Weave': ['red', 'black'],
  '★ Driver Gloves | King Snake': ['green', 'black', 'cyberpunk'],
  '★ Driver Gloves | Imperial Plaid': ['red', 'black'],
  '★ Driver Gloves | Rezan the Red': ['red'],
  '★ Driver Gloves | Lunar Weave': ['white', 'black'],
  '★ Driver Gloves | Black Tie': ['black', 'gold'],
  '★ Driver Gloves | Snow Leopard': ['white', 'gray'],
  '★ Driver Gloves | Diamondback': ['black', 'gold'],
  '★ Driver Gloves | Racing Green': ['green', 'black'],
  '★ Driver Gloves | Convoy': ['gray', 'green', 'military'],

  '★ Specialist Gloves | Crimson Kimono': ['red', 'black'],
  '★ Specialist Gloves | Crimson Web': ['red', 'black'],
  '★ Specialist Gloves | Marble Fade': ['pink', 'red', 'doppler-family'],
  '★ Specialist Gloves | Fade': ['pink', 'purple', 'doppler-family'],
  '★ Specialist Gloves | Tiger Strike': ['orange', 'black'],
  '★ Specialist Gloves | Emerald Web': ['green', 'black'],
  '★ Specialist Gloves | Foundation': ['orange', 'gold'],
  '★ Specialist Gloves | Buckshot': ['orange', 'gold'],
  '★ Specialist Gloves | Field Agent': ['gray', 'orange', 'military'],
  '★ Specialist Gloves | Mogul': ['purple', 'black'],

  '★ Hand Wraps | Slaughter': ['red'],
  '★ Hand Wraps | Cobalt Skulls': ['blue'],
  '★ Hand Wraps | Overprint': ['red', 'black'],
  '★ Hand Wraps | Leather': ['black', 'vintage'],
  '★ Hand Wraps | Spruce DDPAT': ['gray', 'military'],
  '★ Hand Wraps | Desert Shamagh': ['orange', 'gold'],
  '★ Hand Wraps | Constrictor': ['red', 'black'],
  '★ Hand Wraps | Giraffe': ['orange', 'black'],
  '★ Hand Wraps | Arboreal': ['green', 'military'],

  '★ Moto Gloves | Spearmint': ['green', 'white'],
  '★ Moto Gloves | Polygon': ['blue', 'gold', 'cyberpunk'],
  '★ Moto Gloves | Cool Mint': ['green', 'white'],
  '★ Moto Gloves | POW!': ['red', 'orange'],
  '★ Moto Gloves | Boom!': ['orange', 'red'],
  '★ Moto Gloves | Eclipse': ['black', 'orange'],
  '★ Moto Gloves | Smoke Out': ['white', 'gray'],
  '★ Moto Gloves | Transport': ['orange', 'black'],

  '★ Bloodhound Gloves | Charred': ['black', 'red'],
  '★ Bloodhound Gloves | Snakebite': ['orange', 'green'],
  '★ Bloodhound Gloves | Bronzed': ['orange', 'gold', 'military'],
  '★ Bloodhound Gloves | Guerrilla': ['green', 'red'],
  '★ Bloodhound Gloves | Yellow Jacket': ['orange', 'gold'],

  '★ Broken Fang Gloves | Jade': ['green', 'gold'],
  '★ Broken Fang Gloves | Yellow-banded': ['orange', 'gold'],
  '★ Broken Fang Gloves | Needle Point': ['blue', 'orange'],
  '★ Broken Fang Gloves | Unhinged': ['red', 'black'],

  '★ Hydra Gloves | Case Hardened': ['blue', 'gold', 'vintage'],
  '★ Hydra Gloves | Emerald': ['green', 'gold'],
  '★ Hydra Gloves | Mangrove': ['green', 'orange'],
  '★ Hydra Gloves | Rattler': ['gray', 'orange'],

  // ====== Other popular guns ======
  // P250
  'P250 | Asiimov': ['orange', 'white', 'cyberpunk'],
  'P250 | Mehndi': ['orange', 'black', 'vintage'],
  'P250 | Cartel': ['gold', 'black'],
  'P250 | See Ya Later': ['pink', 'cyberpunk', 'neon'],
  'P250 | Splash': ['blue', 'pink'],
  'P250 | Nuclear Threat': ['green', 'yellow'],
  'P250 | Visions': ['red', 'orange'],
  'P250 | Wingshot': ['orange', 'red'],
  'P250 | Whiteout': ['white', 'gray'],
  'P250 | Re.built': ['orange', 'gold'],
  'P250 | Inferno': ['orange', 'red'],
  'P250 | Apep\'s Curse': ['gold', 'green'],
  'P250 | Crimson Kimono': ['red', 'black'],
  'P250 | Cassette': ['black', 'white'],

  // Five-SeveN
  'Five-SeveN | Case Hardened': ['blue', 'gold', 'vintage'],
  'Five-SeveN | Hyper Beast': ['pink', 'blue', 'neon'],
  'Five-SeveN | Monkey Business': ['orange', 'green'],
  'Five-SeveN | Fall Hazard': ['orange', 'black'],
  'Five-SeveN | Neon Kimono': ['orange', 'red', 'neon'],
  'Five-SeveN | Angry Mob': ['blue', 'white'],
  'Five-SeveN | Capillary': ['red', 'white'],
  'Five-SeveN | Boost Protocol': ['blue', 'green', 'cyberpunk'],
  'Five-SeveN | Crimson Blossom': ['red', 'pink'],
  'Five-SeveN | Anodized Gunmetal': ['gray', 'black'],
  'Five-SeveN | Forest Night': ['green', 'military'],

  // Tec-9
  'Tec-9 | Fuel Injector': ['red', 'black'],
  'Tec-9 | Decimator': ['pink', 'purple', 'neon'],
  'Tec-9 | Nuclear Threat': ['green', 'yellow'],
  'Tec-9 | Avalanche': ['blue', 'white'],
  'Tec-9 | Hades': ['orange', 'red'],
  'Tec-9 | Cracked Opal': ['orange', 'green'],
  'Tec-9 | Brass': ['gold', 'orange'],
  'Tec-9 | Mummy\'s Rot': ['orange', 'gold'],
  'Tec-9 | Rebel': ['red', 'black'],
  'Tec-9 | Bamboozle': ['green', 'orange'],
  'Tec-9 | Toxic': ['green', 'neon'],
  'Tec-9 | Ice Cap': ['blue', 'white'],
  'Tec-9 | Blue Blast': ['blue', 'cyberpunk'],

  // Tec-9, Dual Berettas, Mac-10, MP9, MP7, P90, UMP-45, PP-Bizon, MP5-SD
  'Dual Berettas | Cobra Strike': ['black', 'gold'],
  'Dual Berettas | Marina': ['blue', 'orange'],
  'Dual Berettas | Melondrama': ['green', 'orange'],
  'Dual Berettas | Twin Turbo': ['blue', 'red'],
  'Dual Berettas | Flora Carnivora': ['green', 'pink'],

  'MAC-10 | Neon Rider': ['pink', 'cyberpunk', 'neon'],
  'MAC-10 | Stalker': ['orange', 'green', 'cyberpunk'],
  'MAC-10 | Disco Tech': ['pink', 'cyberpunk', 'neon'],
  'MAC-10 | Heat': ['orange', 'red'],
  'MAC-10 | Tatter': ['orange', 'black'],
  'MAC-10 | Toybox': ['pink', 'blue'],
  'MAC-10 | Last Dive': ['blue', 'pink'],
  'MAC-10 | Curse': ['black', 'red'],
  'MAC-10 | Sakkaku': ['orange', 'red'],
  'MAC-10 | Calf Skin': ['white', 'orange'],
  'MAC-10 | Nuclear Garden': ['green', 'orange'],

  'MP9 | Wild Lily': ['white', 'pink'],
  'MP9 | Hot Rod': ['red', 'orange'],
  'MP9 | Bulldozer': ['orange', 'black'],
  'MP9 | Hypnotic': ['gold', 'black'],
  'MP9 | Featherweight': ['gray', 'white'],

  'MP7 | Whiteout': ['white', 'red'],
  'MP7 | Bloodsport': ['red', 'pink'],
  'MP7 | Nemesis': ['blue', 'purple'],
  'MP7 | Fade': ['pink', 'purple', 'doppler-family'],

  'P90 | Asiimov': ['orange', 'white', 'cyberpunk'],
  'P90 | Death by Kitty': ['pink', 'purple'],
  'P90 | Trigon': ['black', 'orange'],
  'P90 | Cold Blooded': ['black', 'orange'],
  'P90 | Emerald Dragon': ['green', 'gold'],

  'UMP-45 | Primal Saber': ['red', 'orange'],
  'UMP-45 | Blaze': ['orange', 'red'],
  'UMP-45 | Crime Scene': ['orange', 'red'],

  'PP-Bizon | Judgement of Anubis': ['gold', 'black'],
  'PP-Bizon | High Roller': ['gold', 'red'],
  'PP-Bizon | Embargo': ['orange', 'red'],

  // ====== AUG / SG 553 / FAMAS / Galil ======
  'AUG | Akihabara Accept': ['pink', 'white'],
  'AUG | Bengal Tiger': ['orange', 'black'],
  'AUG | Wings': ['white', 'gold'],
  'AUG | Chameleon': ['green', 'blue'],
  'AUG | Stymphalian': ['blue', 'gold'],
  'AUG | Flame Jörmungandr': ['blue', 'red', 'gold'],
  'AUG | Hot Rod': ['red', 'orange'],
  'AUG | Death by Puppy': ['pink', 'white'],

  'SG 553 | Pulse': ['blue', 'cyberpunk'],
  'SG 553 | Cyrex': ['white', 'red', 'cyberpunk'],
  'SG 553 | Integrale': ['blue', 'red'],
  'SG 553 | Bulldozer': ['orange', 'black'],
  'SG 553 | Hazard Pay': ['orange', 'gold'],
  'SG 553 | Cyberforce': ['blue', 'cyberpunk', 'neon'],

  'FAMAS | Mecha Industries': ['blue', 'orange', 'cyberpunk'],
  'FAMAS | Roll Cage': ['orange', 'black'],
  'FAMAS | Eye of Athena': ['gold', 'white'],
  'FAMAS | Afterimage': ['pink', 'blue'],
  'FAMAS | Pulse': ['blue', 'cyberpunk'],

  'Galil AR | Cerberus': ['black', 'red'],
  'Galil AR | Chatterbox': ['orange', 'black', 'cyberpunk'],
  'Galil AR | Phoenix Blacklight': ['orange', 'red'],
  'Galil AR | Eco': ['orange', 'green'],
  'Galil AR | Stone Cold': ['white', 'gray'],
  'Galil AR | Sugar Rush': ['pink', 'purple'],
  'Galil AR | Green Apple': ['green'],
  'Galil AR | Destroyer': ['orange', 'gray'],

  // ====== SSG 08, SCAR-20, G3SG1, R8 ======
  'SSG 08 | Blood in the Water': ['red', 'blue'],
  'SSG 08 | Big Iron': ['orange', 'gold'],
  'SSG 08 | Death\'s Head': ['white', 'black'],
  'SSG 08 | Detour': ['orange', 'black'],
  'SSG 08 | Dragonfire': ['orange', 'red'],
  'SSG 08 | Hot Shot': ['orange', 'black'],
  'SSG 08 | Sea Calico': ['blue', 'pink'],

  'SCAR-20 | Bloodsport': ['red', 'pink'],
  'SCAR-20 | Cardiac': ['red', 'orange'],
  'SCAR-20 | Cyrex': ['white', 'red', 'cyberpunk'],
  'SCAR-20 | Brass': ['gold', 'orange'],
  'SCAR-20 | Emerald': ['green', 'gold'],

  'G3SG1 | Flux': ['orange', 'red'],
  'G3SG1 | Chronos': ['orange', 'gold'],

  'R8 Revolver | Fade': ['pink', 'purple', 'doppler-family'],
  'R8 Revolver | Llama Cannon': ['orange', 'gold'],
  'R8 Revolver | Crazy 8': ['orange', 'red'],

  // ====== Heavy (Nova, XM1014, MAG-7, Sawed-Off, M249, Negev) ======
  'Nova | Hyper Beast': ['pink', 'blue', 'neon'],
  'Nova | Bloomstick': ['red', 'pink'],
  'Nova | Antique': ['gold', 'orange', 'vintage'],
  'Nova | Sobakaesque': ['blue', 'orange'],
  'Nova | Walnut': ['orange', 'vintage'],
  'Nova | Tempest': ['blue', 'green'],

  'XM1014 | Heaven Guard': ['white', 'gold'],
  'XM1014 | Tranquility': ['blue', 'green'],
  'XM1014 | XOXO': ['pink', 'red'],
  'XM1014 | Frost Borre': ['blue', 'white'],
  'XM1014 | Slipstream': ['blue', 'white'],
  'XM1014 | Banana Leaf': ['green'],

  'MAG-7 | Justice': ['gold', 'orange'],
  'MAG-7 | Bulldozer': ['orange', 'black'],
  'MAG-7 | Sonar': ['blue', 'orange'],
  'MAG-7 | Heat': ['orange', 'red'],
  'MAG-7 | Insomnia': ['blue', 'purple', 'cyberpunk'],

  'Sawed-Off | The Kraken': ['blue', 'red'],
  'Sawed-Off | Wasteland Princess': ['orange', 'green'],
  'Sawed-Off | Devourer': ['green', 'pink'],
  'Sawed-Off | Origami': ['white', 'red'],

  'M249 | Nebula Crusader': ['blue', 'purple'],
  'M249 | Aztec': ['orange', 'gold'],

  'Negev | Loudmouth': ['orange', 'red'],
  'Negev | Power Loader': ['orange', 'black'],
};
